### PR TITLE
TOF: Update digit task with fixes

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Ciao @njacazio , Is this needed for the ongoing MC?

**Comment by njacazio** [comment]
Hi, apologies for the large amount of changes but this is needed as we need to uniform the naming.
Also, as soon as this is closed I will be renaming the task files

**Comment by njacazio** [comment]
@Barthelemy @knopers8 this should also fix an issue introduced with https://github.com/AliceO2Group/QualityControl/pull/1136 that breaks the code if a flag is turned off. Could you give a review ? Thanks!

**Comment by sawenzel** [comment]
@njacazio : There appears to be a real compile error on MacOS:
```
/System/Volumes/Data/build/ci_checks/alice_ci_0/qualitycontrol-o2/sw/SOURCES/QualityControl/1126/0/Modules/TOF/src/CheckRawToT.cxx:58:33: error: result of comparison of constant 18446744073709551615 with expression of type 'bool' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
    if (mo->getName() == "ToT/" != std::string::npos) {
        ~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
```

**Comment by njacazio** [comment]
@sawenzel thanks a lot for spotting this, I will fix it

**Comment by noferini** [comment]
I did a check and this PR is needed also for MC.
In the meanwhile we will exclude TOF digit QC from running MC production

**Comment by chiarazampolli** [comment]
Dear @Barthelemy , @ktf , @knopers8 , 

Can this be merged?

Cheers,

Chiara

**Review by Barthelemy — APPROVED** [review]
